### ISSUE TITLE
`keypress` event issue, is it necessary to optimize.

### ISSUE THREAD

**Issue by dnknn** [github/hotkey#37]
Hi~ I am not a developer and do not understand internal code,

- ## 💥 Current bugged behavior: 
　　　　`keypress` ꘌ `keydown` / `keyup`

- ## ❥ Expected/fixed behavior: 
　　　　`keypress` ≠ `keydown` / `keyup`

---
Add a e.g. `30ms` delay to `keydown` to judge `keypress` event ?

see more at:     https://github.com/Mottie/GitHub-userscripts/issues/136

**Comment by keithamus** [comment]
Thanks for the issue @dnknn. 

I believe what you're asking for us to do is measure a full keypress, which includes the keyup event, such that holding down a button doesn't cause keycombos with duplicate keys (e.g. `t t`) to fire. If my understanding of this issue is wrong please let me know.

While this is a reasonable position, the additional complexity required to implement this outweighs the benefits for us. We currently don't have any keycombos which require duplicate keys, so adding this code would not improve use cases for us. Because of this I'm going to mark this as `wontfix`. We can continue the discussion further if you'd like, but I'm going to close the issue for now.

**Comment by dnknn** [comment]
First of all thank you very much for your reply!
Okay, understand, I thought it could be easily fixed before I put it forward, this is not a big problem.
