### ISSUE TITLE
Add support for `Space` and `Plus` keywords

### ISSUE THREAD

**Issue by laserlemon** [github/hotkey#45]
It seems that the `eventToHotkeyString` function returns `" "` for a spacebar keystroke, as described in the [key values docs](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values#whitespace_keys). But the [`expandHotkeyToEdges` function](https://github.com/github/hotkey/blob/04b4bcfe449bec8e3f1d11d7a2c5dddbb73f7ca1/src/utils.ts#L24-L26) also uses the space character to split hotkey combinations.

So how might one define a single hotkey or hotkey combination containing a space?

We might consider a slight deviation from the key values docs in this instance to add the <kbd>Space</kbd> shorthand as an alias for `" "` when defining a hotkey via the `data-hotkey` attribute or `install` function. Thank you! 💛

**Comment by theinterned** [comment]
Maybe we could use `"Space"` as a way to distinguish space as a separator of key sequences (`" "`), and the literal space key as a shortcut (`"Space"`).

So for example the shortcut key to open Spotlight / Alfred / Raycast on a Mac would be `"Meta+Space"`.

**Comment by theinterned** [comment]
This actually relates to https://github.com/github/hotkey/issues/54#issuecomment-992997472 where I suggest we match on `event.code` rather than `event.key`. The `event.key` for space is `" "`: the `event.code` is `"Space"`, so making that breaking change would also resolve this issue.

If we don't make that change, then this would require some special code.

**Comment by iansan5653** [comment]
Updated this issue to also cover `Plus` (because `Mod++` isn't great).

**Comment by iansan5653** [comment]
Typo prevented this from properly closing when it was merged.
